import Head from "next/head";
import FirstCustomerExperienceCard from "../components/FirstCustomerExperienceCard";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import FirstTestimonial from "../components/TestimonialDataOne";
import SecondTestimonial from "../components/TestimonialDataTwo";
import TestimonialCard from "../components/TestimonialCard";
import SecondCustomerExperienceCard from "../components/SecondCustomerExperienceCard";
import CTA from "../components/CTA";
import Footer from "../components/Footer";

const FirstTestimonialCard = FirstTestimonial.map((testimonial) => (
  <TestimonialCard
    key={testimonial.id}
    img={testimonial.img}
    name={testimonial.name}
    location={testimonial.location}
    user={testimonial.user}
    testimonial={testimonial.testimonial}
  />
));

const SecondTestimonialCard = SecondTestimonial.map((testimonial) => (
  <TestimonialCard
    key={testimonial.id}
    img={testimonial.img}
    name={testimonial.name}
    location={testimonial.location}
    user={testimonial.user}
    testimonial={testimonial.testimonial}
  />
));

const FirstCustomerExperience = <FirstCustomerExperienceCard
key={1}
name='Tolu & Joy’s Experience'
img='https://drive.google.com/uc?export=view&id=1PB-Oj4st1LVGbL7SIZSn6b2XJyFgX2jc'
user='CUSTOMER'
testimonial='I had the best experience shopping with vasiti. Usability of the website was great, very good customer service, an all round great experience. I would definately be coming back! I had the best experience shopping with vasiti. Usability of the website was great, very good customer service, an all round great experience. I would definately be coming back!'
color='dark'
/>

const SecondCustomerExperience = <SecondCustomerExperienceCard
key={1}
name='Josiah’s Experience'
img='https://drive.google.com/uc?export=view&id=1GRKdr8VC5ufeC2-hBDOlwNVrJk6luKHS'
user='VENDOR'
testimonial='I had the best experience shopping with vasiti. Usability of the website was great, very good customer service, an all round great experience. I would definately be coming back! I had the best experience shopping with vasiti. Usability of the website was great, very good customer service, an all round great experience. I would definately be coming back!'
color='light'
/>

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vasiti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Hero />
        {/* <CustomerExperience /> */}
        {FirstCustomerExperience}
        <div className={styles.testimonial}>{FirstTestimonialCard}</div>
        {SecondCustomerExperience}
        <div className={styles.testimonial}>{SecondTestimonialCard}</div>
        <CTA/>
      </main>
      <Footer/>
    </div>
  );
}
